@echo off
REM AKIRA 4.0 Windows Launcher
REM Auto-generated by AKIRA Self-Generation API
REM Generated: 2026-01-27T17:29:39.744132

setlocal enabledelayedexpansion

echo.
echo ╔════════════════════════════════════════╗
echo ║   AKIRA 4.0 - Windows Launcher        ║
echo ║   Self-Generated Deployment Package   ║
echo ╚════════════════════════════════════════╝
echo.

REM Check Python installation
python --version >nul 2>&1
if errorlevel 1 (
    echo ❌ Python not found. Please install Python 3.11+
    pause
    exit /b 1
)

echo ✅ Python found
python --version

REM Check pip
pip --version >nul 2>&1
if errorlevel 1 (
    echo ❌ pip not found
    pause
    exit /b 1
)

echo ✅ pip found

REM Create virtual environment
echo.
echo 📦 Creating virtual environment...
if not exist "venv" (
    python -m venv venv
    echo ✅ Virtual environment created
) else (
    echo ✅ Virtual environment already exists
)

REM Activate virtual environment
call venv\Scripts\activate.bat

REM Install dependencies
echo.
echo 📥 Installing dependencies...
pip install -r requirements.txt

REM Start Redis (optional - requires Redis for Windows)
echo.
echo 🔴 Redis status check...
redis-cli ping >nul 2>&1
if errorlevel 1 (
    echo ⚠️  Redis not running. Install Redis for Windows or use WSL2
) else (
    echo ✅ Redis is running
)

REM Start PostgreSQL (optional)
echo.
echo 🐘 PostgreSQL status check...
psql --version >nul 2>&1
if errorlevel 1 (
    echo ⚠️  PostgreSQL not found. Install PostgreSQL or use Docker
) else (
    echo ✅ PostgreSQL found
)

REM Start AKIRA
echo.
echo 🚀 Starting AKIRA 4.0...
echo.
python -m akira_4_0.core.main_orchestrator

pause
