# AKIRA 4.0 Windows PowerShell Launcher
# Auto-generated by AKIRA Self-Generation API
# Generated: 2026-01-27T17:29:39.744135

Write-Host ""
Write-Host "╔════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "║   AKIRA 4.0 - PowerShell Launcher     ║" -ForegroundColor Cyan
Write-Host "║   Self-Generated Deployment Package   ║" -ForegroundColor Cyan
Write-Host "╚════════════════════════════════════════╝" -ForegroundColor Cyan
Write-Host ""

# Check Python
Write-Host "🔍 Checking Python installation..." -ForegroundColor Yellow
$pythonCheck = python --version 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Host "❌ Python not found. Please install Python 3.11+" -ForegroundColor Red
    exit 1
}
Write-Host "✅ Python found: $pythonCheck" -ForegroundColor Green

# Check pip
Write-Host "🔍 Checking pip..." -ForegroundColor Yellow
pip --version | Out-Null
if ($LASTEXITCODE -ne 0) {
    Write-Host "❌ pip not found" -ForegroundColor Red
    exit 1
}
Write-Host "✅ pip is available" -ForegroundColor Green

# Create virtual environment
Write-Host ""
Write-Host "📦 Setting up virtual environment..." -ForegroundColor Yellow
if (-not (Test-Path "venv")) {
    python -m venv venv
    Write-Host "✅ Virtual environment created" -ForegroundColor Green
} else {
    Write-Host "✅ Virtual environment already exists" -ForegroundColor Green
}

# Activate virtual environment
& ".\venv\Scripts\Activate.ps1"

# Install dependencies
Write-Host ""
Write-Host "📥 Installing dependencies..." -ForegroundColor Yellow
pip install -r requirements.txt

# Check Redis
Write-Host ""
Write-Host "🔴 Checking Redis..." -ForegroundColor Yellow
redis-cli ping 2>&1 | Out-Null
if ($LASTEXITCODE -ne 0) {
    Write-Host "⚠️  Redis not running. Install Redis for Windows or use WSL2" -ForegroundColor Yellow
} else {
    Write-Host "✅ Redis is running" -ForegroundColor Green
}

# Check PostgreSQL
Write-Host ""
Write-Host "🐘 Checking PostgreSQL..." -ForegroundColor Yellow
psql --version 2>&1 | Out-Null
if ($LASTEXITCODE -ne 0) {
    Write-Host "⚠️  PostgreSQL not found. Install PostgreSQL or use Docker" -ForegroundColor Yellow
} else {
    Write-Host "✅ PostgreSQL found" -ForegroundColor Green
}

# Start AKIRA
Write-Host ""
Write-Host "🚀 Starting AKIRA 4.0..." -ForegroundColor Green
Write-Host ""
python -m akira_4_0.core.main_orchestrator
